[package]
name = "day1"
version = "0.1.0"
edition = "2021"

[dependencies]
input = { workspace = true }
abs-diff = { workspace = true }
rayon = { workspace = true }
num = { workspace = true }
itertools = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
