[package]
name = "day3"
version = "0.1.0"
edition = "2021"

[dependencies]
input = { workspace = true }
rayon = { workspace = true }
num = { workspace = true }
itertools = { workspace = true }
nom = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
